addSbtPlugin("com.timushev.sbt"   % "sbt-updates"                   % "0.7.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"                 % "0.13.1")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"                % "1.12.0")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies"     % "0.3.1")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"               % "1.1.6")
addSbtPlugin("com.github.sbt"     % "sbt-header"                    % "5.11.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.22.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.12")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.6.1")
addSbtPlugin("pl.project13.scala" % "sbt-jcstress"                  % "0.2.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"                 % "2.4.4")
addSbtPlugin("dev.zio"            % "zio-sbt-website"               % "0.6.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.14.7")

libraryDependencies += "org.snakeyaml" % "snakeyaml-engine" % "3.0.1"
