name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  SBT_OPTS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # Needed for sbt

on:
  pull_request:
  push:
    branches: ['series/2.x']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Lint code
        run: sbt "++2.12.x; check; ++2.13.x; check; ++3.3.x; check"

  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        scala: ['2.13.x', '3.x']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Compile benchmarks
        run: sbt ++${{ matrix.scala }} jmh:compile

  mdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Check Document Generation
        run: sbt compileDocs

  testCross:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        scala: ['2.12.x', '2.13.x', '3.x']
        platform: ['JVM', 'JS', 'Native']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Install Boehm GC
        if: ${{ startsWith(matrix.platform, 'Native') }}
        run: sudo apt-get update && sudo apt-get install -y libgc-dev
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Install libuv
        if: matrix.platform == 'Native'
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Run Macros tests
        if: ${{ !startsWith(matrix.scala, '3.') }}
        run: sbt ++${{ matrix.scala }} testScala2${{ matrix.platform }}
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test${{ matrix.platform }}

  testJVM:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['21', '25'] # Test on 17 is covered in 'testCross' job
        scala: ['2.12.x', '2.13.x', '3.x']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Install Boehm GC
        if: ${{ startsWith(matrix.platform, 'Native') }}
        run: sudo apt-get update && sudo apt-get install -y libgc-dev
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Run Macros tests
        if: ${{ !startsWith(matrix.scala, '3.') }}
        run: sbt ++${{ matrix.scala }} testScala2${{ matrix.platform }}
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test${{ matrix.platform }}


  mima_check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: git fetch --depth=300 origin +refs/tags/*:refs/tags/*
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: sbt +mimaReportBinaryIssues

  ci:
    runs-on: ubuntu-latest
    needs: [lint, mdoc, benchmarks, testCross, testJVM, mima_check]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ci]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
