name: Website

on:
  push:
    branches: [develop]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - run: sbt docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
